name: Build Docker Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  NAME: ppf-contact-solver-base
jobs:
  build-image:
    runs-on: ppf-contact-solver-NVIDIA
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.NAME }}:latest