name: vast.ai

# To setup a vast instance as a self-runner
# set this before running config.py
# export RUNNER_ALLOW_RUNASROOT="1"

on:
  workflow_dispatch:

jobs:
  headless:
    runs-on: vast-ci

    steps:

      - name: check out repo
        uses: actions/checkout@v3

      - name: setup 
        run: |
          nvidia-smi
          apt update
          apt install -y curl git python3 python3-pip
          pip3 install psutil click

      - name: warmup
        run: python3 warmup.py

      - name: build
        run: /root/.cargo/bin/cargo build --release

      - name: run headless
        run: python3 examples/headless.py
