# File: getting-started-vast.yml
# Author: Ryoichi Ando (ryoichi.ando@zozo.com)
# License: Apache v2.0

name: vast.ai

# To setup a vast instance as a self-runner
# set this before running config.py
# export RUNNER_ALLOW_RUNASROOT="1"

on:
  workflow_dispatch:

jobs:
  headless:
    runs-on: vast-ci # replace with your runner name
    timeout-minutes: 15

    steps:

      - name: check out repo
        uses: actions/checkout@v3

      - name: setup 
        run: |
          nvidia-smi
          apt update
          apt install -y git python3

      - name: warmup
        run: python3 warmup.py

      - name: build
        run: /root/.cargo/bin/cargo build --release

      - name: run headless
        run: python3 examples/headless.py
