# File: vast-all.yml
# Author: Ryoichi Ando (ryoichi.ando@zozo.com)
# License: Apache v2.0

name: All Examples

on:
  workflow_dispatch:
    inputs:
      runner:
        type: string
        required: true
        description: 'Runner Name'

env:
  VAST_API_KEY: ${{ secrets.VAST_API_KEY }}
  HELPER_PATH: .github/workflows/vast/helper.sh
  
jobs:
  part_1:
    runs-on: ${{ github.event.inputs.runner }}
    timeout-minutes: 300
    steps:

      - name: check out repo
        uses: actions/checkout@v3

      - name: prepare
        timeout-minutes: 30
        run: bash $HELPER_PATH create $VAST_API_KEY
          
      - name: hang
        run: bash $HELPER_PATH run hang.py

      - name: needle
        run: bash $HELPER_PATH run needle.py

      - name: curtain
        run: bash $HELPER_PATH run curtain.py

      - name: drape
        run: bash $HELPER_PATH run drape.py
      
      - name: trapped
        run: bash $HELPER_PATH run trapped.py
      
      - name: cards
        run: bash $HELPER_PATH run cards.py

      - name: shutdown
        if: always()
        run: bash $HELPER_PATH delete

  part_2:
    runs-on: ${{ github.event.inputs.runner }}
    timeout-minutes: 300
    steps:

      - name: check out repo
        uses: actions/checkout@v3

      - name: prepare
        timeout-minutes: 30
        run: bash $HELPER_PATH create $VAST_API_KEY

      - name: stack
        run: bash $HELPER_PATH run stack.py

      - name: shutdown
        if: always()
        run: bash $HELPER_PATH delete

  part_3:
    runs-on: ${{ github.event.inputs.runner }}
    timeout-minutes: 300
    steps:

      - name: check out repo
        uses: actions/checkout@v3

      - name: prepare
        timeout-minutes: 30
        run: bash $HELPER_PATH create $VAST_API_KEY

      - name: friction
        run: bash $HELPER_PATH run friction.py

      - name: shutdown
        if: always()
        run: bash $HELPER_PATH delete
  
  part_4:
    runs-on: ${{ github.event.inputs.runner }}
    timeout-minutes: 300
    steps:

      - name: check out repo
        uses: actions/checkout@v3

      - name: prepare
        timeout-minutes: 30
        run: bash $HELPER_PATH create $VAST_API_KEY

      - name: trampoline
        run: bash $HELPER_PATH run trampoline.py

      - name: shutdown
        if: always()
        run: bash $HELPER_PATH delete
